# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16GQ4eNL3korg-ZLk_46GxDfQ6Qx6AHx-
"""

import seaborn as sns
import matplotlib.pyplot as plt

# Load sample data
tips = sns.load_dataset("tips")

# Distribution plot with histogram & KDE
sns.displot(tips['total_bill'], kde=True, bins=20)

plt.show()

# Scatter plot with marginal histograms
sns.jointplot(data=tips, x="total_bill", y="tip", kind="scatter", marginal_kws=dict(bins=20, fill=True))

plt.show()

# Pairplot to visualize multiple relationships
sns.pairplot(tips, hue="sex", diag_kind="kde")

plt.show()

# Rugplot for total bill
sns.rugplot(tips['total_bill'])

plt.show()

# KDE Plot for smooth distribution
sns.kdeplot(tips['total_bill'], shade=True)

plt.show()